[package]
name = "selvage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
erased-serde = "0.3.31"
futures-intrusive = "0.5.0"
itertools = "0.11.0"
kurbo = {"path" = "/home/matt/git/kurbo", features = ["serde", "schemars"]}
peniko = {"path" = "/home/matt/git/peniko", features = ["serde", "schemars"]}
png = "0.17.10"
pollster = "0.3.0"
schemars = "0.8.15"
serde = {"version" = "1.0.190", features=["derive", "rc"]}
serde_json = "1.0.107"
svg = "0.14.0"
thiserror = "1.0.50"
vello = { path = "/home/matt/git/vello", features = ["serde", "schemars"] }
wgpu = "0.17.0"
